spring:
  application:
    name: Shapr
  datasource:
    url: jdbc:postgresql://localhost:5432/shapr
    username: postgres
    password: abc123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
